# Site settings
title: The Portico Project
email: peeps@porticoproject.org
description: "The Portico Project - Open Source HLA: By Jerks, For Jerks."
baseurl: ""
url: "http://timpokorny.github.io"
github_username:  timpokorny

# Build settings
markdown: kramdown
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "autolink", "tables", "with_toc_data"]

kramdown:
    input: GFM

#permalink: pretty

