# Site settings
title: The Portico Project
email: peeps@porticoproject.org
description: "The Portico Project - Open Source HLA: By Jerks, For Jerks."
baseurl: ""
url: "http://timpokorny.github.io"
github_username:  timpokorny
destination: ../public/

# Build settings
markdown: redcarpet
highlighter: none
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "autolink", "tables", "with_toc_data"]

kramdown:
    input: GFM

# We don't use because it's just that much harder to make use of offline.
# You can't link to /relative/url and exepcted /relative/url/index.html to
# be picked up and displayed :(
#permalink: pretty

# Portico specific properties
stable_version: 2.0.0
stable_date: April 1, 2013
nightly_version: 2.0.1
nightly_date: 10 March, 2015
