# Site settings
title: The Portico Project
email: peeps@porticoproject.org
description: "The Portico Project - Open Source HLA: By Jerks, For Jerks."
baseurl: ""
url: "https://timpokorny.github.io"
github_username:  timpokorny
destination: ../public/

# Build settings
markdown: kramdown
highlighter: none

kramdown:
    input: GFM

# We don't use because it's just that much harder to make use of offline.
# You can't link to /relative/url and exepcted /relative/url/index.html to
# be picked up and displayed :(
#permalink: pretty

# Portico specific properties
stable_version: 2.1.0
stable_date: 2 May, 2016
nightly_version: 2.1.0-dev
nightly_date: 2 May, 2016
